# Generated by Django 5.0.4 on 2024-04-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("phone_number", models.IntegerField()),
                ("email", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=200)),
                ("last_name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=200)),
                ("password", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("quantity_in_stock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField()),
                ("total_amount", models.IntegerField()),
                (
                    "note",
                    models.CharField(
                        default="Database design for on counter billing for SPACE-Y",
                        max_length=200,
                    ),
                ),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.customer",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillDetails",
            fields=[
                (
                    "bill_detail_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("quantity", models.IntegerField()),
                ("price", models.IntegerField()),
                (
                    "bill_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="billing.bill"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="billing.product",
                    ),
                ),
            ],
        ),
    ]
