# Generated by Django 5.0.4 on 2024-04-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_bill_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="total_amount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
