# Generated by Django 5.0.4 on 2024-04-10 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_bill_total_amount_alter_product_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billdetail",
            name="price",
        ),
    ]
