# Generated by Django 5.0.4 on 2024-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_remove_billdetail_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="billdetail",
            name="total_cost",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
