openapi: 3.0.3
info:
  title: spacey_billing API
  version: 1.0.0
  description: Create an employee using the register endpoint. Only employees can
    create a new customer. Create delete update products can be performed by employees
    only. List all the products are available to everyone. Bill details CRUD are available
    for customers only. Bill CRUD is available to employees only.
paths:
  /api/v1/auth/login/:
    post:
      operationId: v1_auth_login_create
      tags:
      - v1
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/auth/register/:
    post:
      operationId: v1_auth_register_create
      tags:
      - v1
      security:
      - tokenAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/bill-details/:
    get:
      operationId: v1_bill_details_list
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillDetail'
          description: ''
    post:
      operationId: v1_bill_details_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BillDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BillDetail'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillDetail'
          description: ''
  /api/v1/bill-details/{id}/:
    get:
      operationId: v1_bill_details_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill detail.
        required: true
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillDetail'
          description: ''
    put:
      operationId: v1_bill_details_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill detail.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BillDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/BillDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/BillDetail'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillDetail'
          description: ''
    patch:
      operationId: v1_bill_details_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill detail.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBillDetail'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBillDetail'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBillDetail'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BillDetail'
          description: ''
    delete:
      operationId: v1_bill_details_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill detail.
        required: true
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/bills/:
    get:
      operationId: v1_bills_list
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bill'
          description: ''
    post:
      operationId: v1_bills_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bill'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bill'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bill'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
          description: ''
  /api/v1/bills/{id}/:
    get:
      operationId: v1_bills_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill.
        required: true
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
          description: ''
    put:
      operationId: v1_bills_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bill'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Bill'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Bill'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
          description: ''
    patch:
      operationId: v1_bills_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedBill'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedBill'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedBill'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bill'
          description: ''
    delete:
      operationId: v1_bills_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this bill.
        required: true
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/products/:
    get:
      operationId: v1_products_list
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
    post:
      operationId: v1_products_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - tokenAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
  /api/v1/products/{id}/:
    get:
      operationId: v1_products_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this product.
        required: true
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    put:
      operationId: v1_products_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this product.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
        required: true
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    patch:
      operationId: v1_products_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this product.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedProduct'
      security:
      - tokenAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
    delete:
      operationId: v1_products_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this product.
        required: true
      tags:
      - v1
      security:
      - tokenAuth: []
      responses:
        '204':
          description: No response body
components:
  schemas:
    Bill:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        customer:
          type: integer
        employee:
          type: integer
        total_amount:
          type: string
          readOnly: true
        bill_details:
          type: string
          readOnly: true
      required:
      - bill_details
      - customer
      - employee
      - id
      - total_amount
    BillDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        bill:
          type: integer
        product:
          type: integer
        quantity:
          type: integer
          maximum: 2147483647
          minimum: 0
        price:
          type: string
          readOnly: true
        total_cost:
          type: integer
          maximum: 2147483647
          minimum: 0
      required:
      - bill
      - id
      - price
      - product
      - quantity
    PatchedBill:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        customer:
          type: integer
        employee:
          type: integer
        total_amount:
          type: string
          readOnly: true
        bill_details:
          type: string
          readOnly: true
    PatchedBillDetail:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        bill:
          type: integer
        product:
          type: integer
        quantity:
          type: integer
          maximum: 2147483647
          minimum: 0
        price:
          type: string
          readOnly: true
        total_cost:
          type: integer
          maximum: 2147483647
          minimum: 0
    PatchedProduct:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        price:
          type: integer
          maximum: 2147483647
          minimum: 0
        quantity_in_stock:
          type: integer
          maximum: 2147483647
          minimum: 0
        created:
          type: string
          format: date-time
          readOnly: true
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 200
        price:
          type: integer
          maximum: 2147483647
          minimum: 0
        quantity_in_stock:
          type: integer
          maximum: 2147483647
          minimum: 0
        created:
          type: string
          format: date-time
          readOnly: true
      required:
      - created
      - id
      - name
      - price
      - quantity_in_stock
  securitySchemes:
    tokenAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Token-based authentication with required prefix "Token"
